- Docs/issue_proccess.md
- README.md
- issue_proccess.md 파일에 관련 문서 추가
- README.md에 해당 문서 & 스타일쉐어 컨벤션 문서 연결
> [Doc] 개발 컨벤션 관련 문서 기재

- ShowPot/ShowPot.xcodeproj/project.pbxproj
향후 UI 작업에 사용될 패키지 추가
SPM을 통해 다음 두가지 패키지 추가됨
- [PinLayout](https://github.com/layoutBox/PinLayout)
- [FlexLayout](https://github.com/layoutBox/FlexLayout)
- #16
> [Package] #16 flexlayout, pinlayout 패키지 추가

- ShowPot/ShowPot/Application/SceneDelegate.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/ViewController/FeaturedViewController.swift
- ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/mainGreen.colorset/Contents.json
- 프로젝트에서 사용될 디자인 리소스들이 올바르게 적용되었는지 디자이너에게 확인하기위한 샘플화면 구현
- Color, Image, Text Font 디자인 시스템이 보여지는 화면 구현
**스크린샷**
- 앱 빌드 이후 첫 화면 확인
> [Feature] 디자인시스템을 위한 샘플앱 구현

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Common/UI/Protocol/ReusableCell.swift
- ShowPot/ShowPot/Presentation/Scene/Onboarding/CustomView/OnboardingCarouselCell.swift
- ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewHolder.swift
- `UICollectionView` `UITableVIew` 사용시 `reuseIdentifier` 이용 작업 자동화를 위한 작업
- class 이름을 사용해 자동으로 reuseIdentifier를 생성하는 `ReusableCell` 프로토콜 생성
- 해당 프로토콜을 이용해 기존 온보딩 캐러샐(UICollectionVIew) 리팩토링
**기존 로직**
```swift
class TableCell: UITableViewCell {
static let reuseIdentifier = "TableCell"
}
// Cell register
tableView.register(TableCell, forCellWithReuseIdentifier: TableCell.reuseIdentifier)
// dequeue Cell
let cell = tableView.dequeueReusableCell(withIdentifier: TableCell.reuseIdentifier, for: indexPath) 
```
**변경 로직**
```swift
/// class 이름을 reuseIdentifier로 자동으로 만들어주는 Protocol
protocol ReusableCell: AnyObject {
static var reuseIdentifier: String { get }
}
extension ReusableCell {
static var reuseIdentifier: String {
return String(describing: Self.self)
}
}
// MARK: UICollectionView & …
```
> [Refactor] #46 reuseIdentifier 지정 코드 추가

- ShowPot/ShowPot/Common/UI/Protocol/ReusableCell.swift
- #46 작업에 대한 추가 기능 개발
- `UICollectionView`의 header footer 관련 코드 추가
해당 메서드 추가
```swift
func register<T: UICollectionReusableView>(_: T.Type, of kind: String) where T: ReusableCell {
register(T.self, forSupplementaryViewOfKind: kind, withReuseIdentifier: T.reuseIdentifier)
}
```
- close #70 
- 추후에 `UITableView`에도 추가 기능이 필요할 경우 작업 필요
- 이 PR에서는 `UICollectionView`에 관한 기능만 추가됨
> #70 ReusableCell 프로토콜 header footer 추가 대응

- ShowPot/ShowPot/Common/Font/KRFont.swift
- 폰트 line height & letter spacing 값 수정
- 디자이너에게 컨펌받은 값으로 해당 값들 수정
**기존 로직**
```swift
/// 한국어 폰트 스타일
enum KRFont: LanguageFont {
static var font: CustomFont = .pretendard
static var lineHeightMultiple: CGFloat = 1.5
static var letterSpacing: CGFloat = -0.025
```
**변경 로직**
```swift
/// 한국어 폰트 스타일
enum KRFont: LanguageFont {
static var font: CustomFont = .pretendard
static var lineHeightMultiple: CGFloat = 1.26
static var letterSpacing: CGFloat = -0.03
```
- #68 
- ENFont의 경우 해당 작업에서 추가 수정이 없기 때문에, 추후 수정 가능성 존재
> [Fix] #68 폰트 line height & letter spacing 임시값으로 수정

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
- ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
- ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
- UserDefaults를 사용하기 위한 객체 개발
- `UserDefaultsManager` 개발
- `UserDefaultsKey` 열거형 추가
**변경 로직**
```swift
/// UserDefaults 관리 싱글톤 객체
final class UserDefaultsManager {
static let shared = UserDefaultsManager()
let userDefaults: UserDefaults?
private init() {
self.userDefaults = UserDefaults.standard
}
}
extension UserDefaultsManager {
func remove(for key: UserDefaultsKey) {
self.userDefaults?.removeObject(forKey: key.value)
self.userDefaults?.synchronize()
}
func set<T>(_ object: T, for key: UserDefaultsKey) {
self.userDefaults?.set(object, forKey: key.value)
self.userDefaults?.synchronize()
}
func get<T>(for key: UserDefaultsKey) -> T? {
let result = self.userDefaults?.object(forKey: key.value) as? T
return result
}
func getObject(for key: UserDefaultsKey) -> Any? {
let result = …
```
> [Feature] #49 userdefaults 관리 로직 개발

- ShowPot/.swiftlint.yml
- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Application/AppDelegate.swift
- ShowPot/ShowPot/Application/SceneDelegate.swift
- ShowPot/ShowPot/Common/Font/ENFont.swift
- ShowPot/ShowPot/Common/Font/KRFont.swift
- ShowPot/ShowPot/Common/LogHelper.swift
- ShowPot/ShowPot/Common/UI/PaddingLabel.swift
- ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
- ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedOnlyTitleHeaderView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedRecommendedPerformanceCell.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
- lint 추가
- lint 추가
- 관련해서 새롭게 생성되는 warning / error 수정
- 정상 빌드 확인
- `TODO` 관련 warning 표출되는지 확인
- #74 
- 개인 개발환경에서 정상적으로 작동되는지 확인 필요
- [SwiftLint](https://github.com/realm/SwiftLint)
- [Install SwiftLint via SPM](https://www.youtube.com/watch?v=4xMUxfJKTVM) - target 설정 관련 참고
> [Package] #74 swiftlint 추가

- ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
- 모든 ViewController의 공통 배경색 적용
- `BaseViewController`에서 `view`의 배경색을 `.gray700`으로 적용
- 해당 설정이 이미 개발된 뷰에 적용 가능하도록 수정
**기존 로직**
```swift
class BaseViewController: UIViewController {
func setupStyles() { }
}
```
```swift
final class SavedViewController: ViewController {
override func setupStyles() {
self.view.backgroundColor = .gray700
// 추가 뷰 스타일 설정
}
```
**변경 로직**
```swift
class BaseViewController: UIViewController {
func setupStyles() {
self.view.backgroundColor = .gray700
}
}
```
```swift
final class SavedViewController: ViewController {
override func setupStyles() {
super.setupStyles()
// 추가 뷰 스타일 설정
}
```
- 빌드 성공 확인
- 다른 화면에서 일괄된 배경색 적용 확인
- close #69
> [Feature] #69 BaseViewController에 default BGColor 적용

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- 패키지 추가 및 삭제 
- `PinLayout` `FlexLayout` 삭제
- `RxDatasource` `RxGesture` 추가
- close #102 
- `PinLayout` `FlexLayout` 은 추후 해당 라이브러리로 리팩토링시 패키지 추가
- `RxAlamofire`의 경우 오랜 기간 업데이트 되지 않아 `RxSwift`의 버전을 `6.0.0`까지 내려야 하는 이슈가 있어 미추가
> [Package] #102 PinLayout/FlexLayout 삭제 & RxDatasource/RxGesture 추가

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/NavigationController.swift
- 홈화면 최상단 애니메이션 탑뷰 
- SPNavigationTitleView 개발
- `FeaturedViewHolde`에 추가
- `FeaturedViewController`의 `scrollDelegate`를 이용해 표출/미표출 애니메이션 구현
**스크린샷**
- 홈화면 스크롤 및 동작 확인
- close #75 
- 최상단 뷰의 height 만큼 collection view 최상단에 inset을 넣는 방식으로 해결했기 때문에, 추후 개선 필요
> [Feature] #75 홈화면 상단 로고 & 검색 영역 개발

- ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object Color/gray100.colorset/Contents.json
- ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object Color/gray200.colorset/Contents.json
- ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object Color/gray300.colorset/Contents.json
- gary 컬러 일부 수정
- `gray100` `gray200` `gray300` 컬러 수정
- 컬러값 확인
- close #99
> [fix] #99 gray 컬러 일부 수정

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Common/Extension/BaseViewController+BottomSheet.swift
- ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
- ShowPot/ShowPot/Common/UI/SPButtonStyle.swift
- ShowPot/ShowPot/Common/UI/SPDefaultBottomSheetViewController.swift
- ShowPot/ShowPot/Resource/Localizable/Localizable.strings
- ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
- 바텀시트 관련 기능 추가
- 기본 바텀시트 개발 `BottomSheetViewController`
- 커스텀 바텀시트 개발 `SPDefaultBottomSheetViewController`
- 공용 바텀시트 extension 개발 `BaseViewController+BottomSheet`
**변경 로직**
```swift
let loginBottomSheet = SPDefaultBottomSheetViewController(
message: Strings.bottomSheetLoginMessage,
buttonTitle: Strings.bottomSheetLoginButtonTitle
)
self.presentBottomSheet(viewController: loginBottomSheet)
```
**스크린샷**
- `BaseViewController` 에서 `showLoginBottomSheet()` 코드 추가
- close #109 
- 다른 바텀시트 개발 필요
- [Transform: CGAffineTransform](https://www.hackingwithswift.com/read/15/4/transform-cgaffinetransform)
- [Bottom Sheet View Controller with Dynamic Content Height in iOS](https://levelup.gitconnected.com/bottom-sheet-view-controller-with-dynamic-content-height-in-ios-4160222f738)
> [Feature] #109 바텀시트 개발

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
- ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
- ShowPot/ShowPot/Domain/UseCase/MyAlarm/DefaultMyAlarmUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/MyPage/MyPageUseCase.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MenuCell.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/CustomView/MyPageHeaderView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
- ShowPot/ShowPot/Resource/Localizable/Localizable.strings
- ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
- 마이페이지 관련 UI를 개발 
- 디자인 수정으로 인해 내 공연 메뉴 수정 
- 홈 화면 누락되었던 `hidesBottomBarWhenPushed` 삭제
**기존 로직**
- 이전 마이페이지 화면 없음
**스크린샷**
- 이전 마이페이지 화면 없음
**변경 로직**
- 이전 마이페이지 화면 없음
**스크린샷**
- `마이페이지`화면 확인 
- `SettingViewModel`의 `nickname`을 수정하여 닉네임 존재 여부에 따른 알림텍스트 변경 확인 
- #124 
- 디자인 변경으로 인해 기존 내 공연메인화면에 대한 메뉴 탭을 변경하였습니다, 그에 따라 SwiftGen 변경작업 진행하였고 추후 내 공연메인화면관련 PR로 `티켓팅종료화면`, `관심공연화면`개발하여 올리도록 할게요 
- 이전 PR에서 `hidesBottomBarWhenPushed`삭제한 코드가 누락되어 다음 PR에서 삭제하였습니다
- @ChoiysApple  현재 `setNavigationBarItem`을 이용하고있는데 Inset값이 상이해서 이 부분 고쳐야할꺼같아요
> [Feature] #124 마이페이지 UI 구현

- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeGenreCell.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
https://github.com/user-attachments/assets/dab29bff-a0c2-49f9-9669-261c09f0b188
https://github.com/user-attachments/assets/7b2b4449-f3a2-4f30-9f85-c862013789f8
> [Feature] 홈화면 목데이터 및 로그인버튼 색상 변경

- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailArtistInfoView.swift
- `공연상세화면` 가로 스크롤 인디케이터 히든 처리
- `ScarlingCarouselView`의 가로 scrollIndicator를 히든 처리하였습니다
**기존 로직**
``` swift
lazy var artistCollectionView = UICollectionView(frame: .zero, collectionViewLayout: artistCollectionViewLayout).then {
$0.register(FeaturedSubscribeArtistCell.self)
$0.backgroundColor = .gray700
}
```
**스크린샷**
**변경 로직**
``` swift
lazy var artistCollectionView = UICollectionView(frame: .zero, collectionViewLayout: artistCollectionViewLayout).then {
$0.register(FeaturedSubscribeArtistCell.self)
$0.backgroundColor = .gray700
$0.showsHorizontalScrollIndicator = false <- 히든처리 추가
}
```
**스크린샷**
https://github.com/user-attachments/assets/bf7edeb4-7bfd-4b4d-ac6f-cb12c4a68368
1. 공연상세화면 이동 
2. 아티스트 정보 가로로 스크롤 시 인디케이터 나오는지 확인
- #145
> [Fix] #145 공연상세화면 스크롤 인디케이터 히든

- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
- SwiftLint 함수 최대길이 오류 수정
- 티켓팅알림관련 바텀시트를 표출하는 로직을 함수로 이전
**기존 로직**
**스크린샷**
**변경 로직**
**스크린샷**
> [Hotfix] SwiftLint 경고오류 수정

- ShowPot/ShowPot/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/MyPage/MyPageUseCase.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
- 마이페이지화면에서 공연 미리보기 리스트 삭제
- 마이페이지화면 `최근 공연`관련 섹션 삭제 
**기존 로직**
``` swift
enum MypageSectionType: CaseIterable {
case menu
case recentShow
}
```
- 기존 마이페이지에 대한 섹션을 2가지로 나누어 데이터 관리
**스크린샷**
**변경 로직**
``` swift
func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
viewModel.menuList.count
}
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
let cell = collectionView.dequeueReusableCell(MenuCell.self, for: indexPath) ?? MenuCell()
let model = viewModel.menuList[indexPath.row]
cell.configureUI(
menuImage: model.type.iconImage,
menuTitle: model.type.title,
badgeCount: model.badgeCount
)
return cell
}
```
- `MyPageSection`으로 관리해줄 필요없이 단일 DataSource 적용
**스크린샷**
1. 마이페이지 화면 이동 
- …
> [Fix] #147 마이페이지 최근공연 삭제

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Application/AppDelegate.swift
- ShowPot/ShowPot/Common/LoginState.swift
- ShowPot/ShowPot/Common/TokenManager.swift
- ShowPot/ShowPot/Data/KeyChain/KeyChainAccount.swift
- ShowPot/ShowPot/Data/KeyChain/KeyChainError.swift
- ShowPot/ShowPot/Data/KeyChain/KeyChainManager.swift
- KeyChainManager 추가
- TokenManager 추가
- LoginState 추가
- AppDelegate 에서 FCM 토큰 저장하는 로직 추가
```swift
LoginState.current.   // 아래 값들 중 하나 반환됨
/* 
/// 로그인 안되어 있음
case notLoggedIn
/// 자동 로그인 설정이 되어있음, accessToken 갱신 필요
case autoLoginPending
/// 로그인 되어있음
case loggedIn
*/
```
```swift
// 초기에는 create 해주어야 함
// 토큰 write
TokenManager.shared.setToken(.pushToken) 또는 create 이름의 메서드 사용
// 토큰 read
TokenManager.shared.readToken(.pushToken)
```
> [Feature] #155 로그인 관련 데이터 관리 로직 개발

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Application/AppDelegate.swift
- ShowPot/ShowPot/Common/TokenManager.swift
- ShowPot/ShowPot/Data/Network/SPUserAPI.swift
- ShowPot/ShowPot/Domain/Entity/Users/Request/UserAccessRequest.swift
- ShowPot/ShowPot/Domain/Entity/Users/Request/UserLoginRequest.swift
- ShowPot/ShowPot/Domain/Entity/Users/Request/UserRefreshRequest.swift
- ShowPot/ShowPot/Domain/Entity/Users/Response/UserProfileResponse.swift
- ShowPot/ShowPot/Domain/Entity/Users/Response/UserTokenResponse.swift
**기존 로직**
**스크린샷**
**변경 로직**
**스크린샷**
> [Feature] #162 토큰 재발급 임시 로직 개발

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
- ShowPot/ShowPot/ShowPot.entitlements
**기존 로직**
**스크린샷**
**변경 로직**
**스크린샷**
> [Feature] #156 애플 로그인 구현

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Common/DateFormatterFactory.swift
- ShowPot/ShowPot/Data/Network/SPArtistAPI.swift
- ShowPot/ShowPot/Data/Network/SPSearchAPI.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Request/SearchArtistRequest.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Request/SubscribeArtistListRequest.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Request/SubscribeArtistRequest.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Request/UnsubscribeArtistRequest.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Response/SearchArtistResponse.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Response/SubscribeArtistResponse.swift
- ShowPot/ShowPot/Domain/Entity/Artist/Response/UnsubscribeArtistResponse.swift
- ShowPot/ShowPot/Domain/Entity/Show/Request/SearchShowRequest.swift
- ShowPot/ShowPot/Domain/Entity/Show/Response/SearchShowResponse.swift
- ShowPot/ShowPot/Domain/UseCase/Featured/DefaultFeaturedUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/Search/DefaultSearchUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/Search/SearchUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/DefaultSubscribeArtistUseCase.swift
- ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
https://github.com/user-attachments/assets/8028c3f6-8ec8-4f8c-a4f2-7c4c47761289
> [Feature] #164 검색 API 연동

- ShowPot/ShowPot/Resource/Localizable/Localizable.strings
- ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
- 기존 얍 노션 링크에서 퍼블리싱가능한 링크로 수정
1. 이용약관 링크 변경
* 기존 얍 노션 링크
https://brassy-client-c0a.notion.site/6584c9436a114162b37f2020f2c4a0e9 
* 변경된 퍼블리싱 가능한 링크 
https://luxuriant-neighbor-e45.notion.site/c9a47093644a49299cfbabe81d8dc66a?pvs=4
2. 개인정보처리방침 링크 변경
* 기존 얍 노션 링크
https://brassy-client-c0a.notion.site/  
* 변경된 퍼블리싱 가능한 링크 
https://luxuriant-neighbor-e45.notion.site/d332eb11da37456b818eb596d05015db?pvs=4
**기존 로직**
- `이용약관`을 누를 시 https://brassy-client-c0a.notion.site/6584c9436a114162b37f2020f2c4a0e9 다음 노션으로 이동
- `개인정보처리방침`을 누를 시 https://brassy-client-c0a.notion.site/ 다음 노션으로 이동
**스크린샷**
**변경 로직**
- `이용약관`을 누를 시 https://luxuriant-neighbor-e45.notion.site/c9a47093644a49299cfbabe81d8dc66a?pvs=4 다음 노션으로 이동
- `개인정보처리방침`을 누를 시 https://luxuriant-neighbor-e45.notion.site/d332eb11da37456b818eb596d05015db …
> [Feature] #168 퍼블리싱가능한 노션링크로 수정

- ShowPot/ShowPot.xcodeproj/project.pbxproj
- ShowPot/ShowPot/Common/DateFormatterFactory.swift
- ShowPot/ShowPot/Common/NumberFormatterFactory.swift
- ShowPot/ShowPot/Data/Network/SPArtistAPI.swift
- ShowPot/ShowPot/Data/Network/SPShowAPI.swift
- ShowPot/ShowPot/Domain/Entity/Show/Request/ShowAlarmListRequest.swift
- ShowPot/ShowPot/Domain/Entity/Show/Response/ShowAlarmListResponse.swift
- ShowPot/ShowPot/Domain/Entity/Show/Response/ShowDetailResponse.swift
- ShowPot/ShowPot/Domain/UseCase/MyAlarm/DefaultMyAlarmUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/ShowDetail/ShowDetailUseCase.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MyUpcomingTicketingHeaderView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailSeatInfoView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailTicketInfoView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewHolder.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
https://github.com/user-attachments/assets/0eb21362-d2da-4fdb-936c-a98288bca78f
> [Feature] #175 내공연 및 공연상세

- ShowPot/ShowPot/Data/Network/SPArtistAPI.swift
- ShowPot/ShowPot/Domain/UseCase/Featured/DefaultFeaturedUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/DefaultSubscribeArtistUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/SubscribeArtistUseCase.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewModel.swift
https://github.com/user-attachments/assets/39396d7c-10bb-4a24-90df-76a893904358
> [Feature] #171 아티스트 구독 API 연동

- ShowPot/ShowPot/Common/Extension/Date+Extension.swift
- ShowPot/ShowPot/Common/TokenManager.swift
- ShowPot/ShowPot/Domain/UseCase/InterestShow/DefaultInterestShowUseCase.swift
- ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowAlarmUseCase.swift
- 현재 알림설정된 공연 API 호출시 빈 값이 내려오기 때문에 추후 테스트 필요
> [Feature] #177 알림공연 & 관심공연 API 연결

- ShowPot/ShowPot/Common/UI/SPSnackBar.swift
- ShowPot/ShowPot/Domain/UseCase/Account/DefaultSignInUseCase.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginCoordinator.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
- ShowPot/ShowPot/Resource/Localizable/Localizable.strings
- ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
https://github.com/user-attachments/assets/fdc9ad62-9dc7-4935-acce-f98711a3d428
> [Feature] #188 로그인 성공/실패 시 pop 혹은 스낵바 표출

- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MyAlarmEmptyView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
<내 공연 EmptyView 최신화 시연영상>
https://github.com/user-attachments/assets/28ea8b9c-3261-4459-8e97-fcf1cc634e1b
현재 viewWillAppear 최신화 코드 추가 화면
1. 관심공연
2. 티켓팅종료공연
3. 알림설정공연
4. 내공연화면
5. 공연상세화면
6. 아티스트구독화면
> [Feature] #190 화면 진입 시 최신화 로직 추가

- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
- ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
**기존 로직**
**스크린샷**
**변경 로직**
**스크린샷**
> [Bugfix] #115 홈화면 헤더/푸터 뷰 터치시 화면 중복 push 문제 수정
